### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by mnot**
This is about as far as I can get without some advice/help - `runtests.py` results in a large number of errors along the lines of:

~~~
  File "/Users/mnot/Projects/feedvalidator/src/feedvalidator/media.py", line 58, in <module>
    class media_credit(text,rfc2396_full):
TypeError: Cannot create a consistent method resolution
order (MRO) for bases text, rfc2396_full
~~~

AFAICT this is because multiple inheritance is used to specify behaviours for the various validators, but that changed in the transition to new-style objects (which are the only option in Python 3).

I suspect fixing this will require a pretty serious restructuring of how the parser classes relate to each other. It's not clear to me how much work that involves. It may be better to start from scratch -- thoughts?

For #46.

### CODE REVIEW

**Comment by rubys** [comment]
I don't have permission to push to this pull request.  See https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Meanwhile, I created https://github.com/rubys/feedvalidator/tree/py3 and committed a fix for the MRO errors https://github.com/rubys/feedvalidator/commit/82bd3475d8a4db5cdc289ac4be94906a067e032d.

I've invited you as a collaborator to rubys/feedvalidator.  It is your choice as to where we continue to develop this branch.

**Comment by mnot** [comment]
Happy to switch to that branch.

I'd tried removing the common base classes, but there are still a large number of errors that I _believe_ are due to reliance on methods being called from them in preference to other bases. I suspect it's going to require going through one-by-one...

**Comment by dontcallmedom** [comment]
FWIW, thanks to the  work you both started, I've managed to get to a stage where at least the test suite passes and the service seems mostly functional in branch https://github.com/w3c/feedvalidator/tree/w3c-py3 of the w3c fork.

There are probably still a bunch of harder to find bugs - the most challenging pieces are around the sharp distinction that python3 now enforces between bytes and strings.

**Comment by rubys** [comment]
Dominique - excellent work.  I've added you as a collaborator too.  What are your thoughts on whether those changes should be pushed "upstream" to this repository, or if this repository should be retired in favor of the W3C fork?

**Comment by dontcallmedom** [comment]
I don't have a specific opinion on whether this repo should be retired or not - I guess it depends mostly on whether it will be maintained or not.

If the repo is to stay, I'm happy to take a stab at updating the py3 branch with rebased version of my commits.

**Pull request closed without merging**
